### //--->Para separar los request--->//
POST http://localhost:9000/api/client HTTP/1.1
Content-Type: application/json

{
   "name": "Pepito Cascioni",
   "phone": "3465532896",
   "location": "Berabevu"
}

###
POST http://localhost:9000/api/income HTTP/1.1
Content-Type: application/json

{
   "year": "2022",
   "month":"Noviembre",
   "day": "9",
   "income": ""
}

###
GET http://localhost:9000/api/client HTTP/1.1
###
GET  http://localhost:9000/api/income HTTP/1.1

###
GET http://localhost:9000/api/client/63656605cbd497ce728b9381 HTTP/1.1
###
  
GET http://localhost:9000/api/income/63680ac8efabdb7f520bbdb1 HTTP/1.1


###
PUT http://localhost:9000/api/client/636bf8957e7779ec1799905b HTTP/1.1
Content-Type: application/json

{  
   "name": "Graciela Vasallo",
   "phone": "3465532896",
   "location": "Los Quirquinchos"
}

###
PUT http://localhost:9000/api/income/636bff825c9f134199f82385 HTTP/1.1
Content-Type: application/json

{ 
   "year": "2022",
   "month": "Noviembre",
   "day": "9",
  "income": "9550"
}

###

DELETE http://localhost:9000/api/client/636bfeed5c9f134199f8237b HTTP/1.1

###
DELETE http://localhost:9000/api/income/636bf4d1cf7a1c96253791bb HTTP/1.1

